### ISSUE TITLE
Typo under WHO IS CHURCH.IO?

### ISSUE THREAD

**Issue by toreyheinz** [churchio/website#23]
We are a community of developers, designers, and users who **believes** church software is too expensive and difficult to use.

Should read We are a community of developers, designers, and users who **believe** church software is too expensive and difficult to use.

**Comment by seven1m** [comment]
Nope. The verb agrees with "community" which is singular. You can read this as "We are a community who believes church software is too expensive and difficult to use."

**Comment by seven1m** [comment]
Hmm, upon thinking about it more, I see how it can be easily read the way you read it. Maybe we should reword?

Reopening your issue. :smiley_cat:

**Comment by toreyheinz** [comment]
Yes, I see that the community is the one who is doing the believing. Maybe it could be worded:
"We are developers, designers, and users - a community who believes church software is too expensive and difficult to use." 
or
"We are a community of developers, designers, and users. We believe church software is too expensive and difficult to use, and we're working to change that by creating awesome open source church software."

Tough call, but my first reading of it was ackward. Either way, good stuff, keep it up.

**Comment by seven1m** [comment]
I like your second option. Let's do that. Thanks!

**Comment by seven1m** [comment]
Fixed in aef0f4ff0f532d1ce0557b38f3ef4d28426568af.
