### ISSUE TITLE
Please add us to the Open Source CRM List 

### ISSUE THREAD

**Issue by DawoudIO** [churchio/website#25]
http://www.churchcrm.io/ 

I Like the idea of this page, I hope you don't mind if i create one like it on http://www.churchcrm.io/

Thanks
George

**Comment by juddey** [comment]
Hey @gdawoud, just had a little look myself, that's a great package. Some really useful functionality. 
Feel free to "cough" borrow our ideas. (they're actually @seven1m's ideas, but I'm sure he won't mind me giving them away :)

**Comment by seven1m** [comment]
:+1:

**Comment by seven1m** [comment]
Finished in edfc3144c990f3ba61af06937473d381c44b400a.

(Better late than never. Sorry.)
