### ISSUE TITLE
Church Community App

### ISSUE THREAD

**Issue by JoFCC** [churchio/website#36]
Have you thought of developing an app similar to the now defunct "The Table" or ACS' "The City"?  I am planting a church and simply unable to afford the costs associated with a commercial product such as the City.  We used The Table until the platform was discontinued.  The Table (and the City) are wonderful tools for connecting and discipling people of the church outside the normal church's meeting times.

**Comment by seven1m** [comment]
@JoFCC that's exactly what [OneBody](https://church.io/onebody/) attempts to be -- a community portal site for members to connect. You can create groups, share photos, share bible verses, prayer requests, etc.

OneBody is self-hosted however, so you'll need to pay for hosting it yourself. But you can do that for $10/month on DigitalOcean or another hosting provider.
